server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route                     #路由ID 没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001            #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE       #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**              #断言，路径匹配的进行路由
        - id: payment_route2
          # uri: http://localhost:8001            #路由ID 没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE       #匹配后提供服务的路由地址
          predicates:                           #匹配后提供服务的路由地址
            - Path=/payment/lb/**               #断言，路径匹配的进行路由
            - After=2022-03-10T14:02:03.214+08:00[Asia/Shanghai] #时间之后
            #- Cookie=username,nekoPunch  #需要两个参数，一个是cookie name，一个是正则表达式， 路由规则会通过获取对应的cookie name值和正则表达式去匹配，如果匹配上就执行，否则不执行
            #- Header=X-request-id,\d+  #需要两个参数，一个是属性名称，一个是正则表达式  请求头要求有X-request-id属性并且值为整数的正则表达式
eureka:
  instance:
    hostname: cloud-gateway-service
    #显示页面的实例名称
    instance-id: gateway9527
    #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka